/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gruppe78_DriverBridge */

#ifndef _Included_com_gruppe78_DriverBridge
#define _Included_com_gruppe78_DriverBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gruppe78_DriverBridge
 * Method:    io_init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_gruppe78_DriverBridge_io_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_gruppe78_DriverBridge
 * Method:    io_set_bit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gruppe78_DriverBridge_io_1set_1bit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gruppe78_DriverBridge
 * Method:    io_clear_bit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gruppe78_DriverBridge_io_1clear_1bit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gruppe78_DriverBridge
 * Method:    io_write_analog
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_gruppe78_DriverBridge_io_1write_1analog
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_gruppe78_DriverBridge
 * Method:    io_read_bit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gruppe78_DriverBridge_io_1read_1bit
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_gruppe78_DriverBridge
 * Method:    io_read_analog
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_gruppe78_DriverBridge_io_1read_1analog
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
